### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by metalic112** [jchnlemon/homebridge-telldus#38]
Did a "tail -f /var/log/homebridge.err" and got the following (after the crash):

```
at /usr/local/lib/node_modules/homebridge-telldus/node_modules/telldus-live/telldus-live.js:221:47
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-telldus/node_modules/oauth/lib/oauth.js:421:9)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by mifi** [comment]
do you know how to reproduce this?

**Comment by metalic112** [comment]
Unfortunately not. I have made some changes (not running WLAN anymore), don't know if it will show anymore. Let's close this and I'll reopen if it appears again.
