### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by yabbah** [jchnlemon/homebridge-telldus#41]
When I try using homebridge with this telldus-plugin I got this error when starting up:

`yabbah@ubuntuLabb:~$ homebridge 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-01-30 09:53:01] Loaded plugin: homebridge-legacy-plugins
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.AD2USB'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.Carwings'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.ELKM1'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.FileSensor'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.HomeMatic'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.Tesla'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.X10'
[2017-01-30 09:53:01] Registering accessory 'homebridge-legacy-plugins.mpdclient'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.Domoticz'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.HomeSeer'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.ISY'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.LIFx'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.SmartThings'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.TelldusLive'
[2017-01-30 09:53:01] Registering platform 'homebridge-legacy-plugins.ZWayServer'
[2017-01-30 09:53:01] ---
[2017-01-30 09:53:01] Loaded plugin: homebridge-telldus
[2017-01-30 09:53:01] Registering platform 'homebridge-telldus.Telldus'
[2017-01-30 09:53:01] ---
[2017-01-30 09:53:01] Loaded config.json with 0 accessories and 1 platforms.
[2017-01-30 09:53:01] ---
[2017-01-30 09:53:01] Loading 1 platforms...
[2017-01-30 09:53:01] [Telldus Live!] Initializing Telldus platform...
[2017-01-30 09:53:02] [Telldus Live!] Loading accessories...
[2017-01-30 09:53:02] [Telldus Live!] Logged in with user: xxx@xxx.xx
[2017-01-30 09:53:03] [Telldus Live!] Found 6 sensors in telldus live.
[2017-01-30 09:53:03] [Telldus Live!] Creating accessory with ID 5338456. Name from telldus: Kök
[2017-01-30 09:53:03] [Telldus Live!] Creating accessory with ID 5338463. Name from telldus: Ute framsidan
[2017-01-30 09:53:03] [Telldus Live!] Creating accessory with ID 8998040. Name from telldus: Ute framsidan
[2017-01-30 09:53:03] [Telldus Live!] Creating accessory with ID 8998039. Name from telldus: Inne hall uppe
[2017-01-30 09:53:03] [Telldus Live!] Creating accessory with ID 6231849. Name from telldus: Inne nere hall
[2017-01-30 09:53:03] [Telldus Live!] Creating accessory with ID 6231850. Name from telldus: Ute baksidan
[2017-01-30 09:53:03] [Telldus Live!] Found 29 devices in telldus live.
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 853408. Name from telldus: Datarum Fönsterlampa
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 853410. Name from telldus: Framsidan Ute Vägglampor
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1396975. Name from telldus: Hall Uppe Julbelysning
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1274347. Name from telldus: Hall vägg uppe
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1463276. Name from telldus: Julgran
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1364043. Name from telldus: Kök fönster
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1307586. Name from telldus: Kök fönsterlampa
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1168978. Name from telldus: Kök köksbänk
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1181910. Name from telldus: Postlåda
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1294099. Name from telldus: Trapplampor
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 853411. Name from telldus: Vardagsrum Fönsterlampa Höger
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 853412. Name from telldus: Vardagsrum Fönsterlampa Vänster
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166780. Name from telldus: Alex Fönsterlampa Höger
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166781. Name from telldus: Alex Fönsterlampa Vänster
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1274351. Name from telldus: Hall vägg nere
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166782. Name from telldus: Matildas Fönster
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1194786. Name from telldus: Matildas rum
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166784. Name from telldus: Niklas Fönsterlampa
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166785. Name from telldus: Niklas Laddare
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166786. Name from telldus: Niklas TV Sovrum
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166787. Name from telldus: Uteplats Bord
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166788. Name from telldus: Uteplats pump
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1181632. Name from telldus: Uteplats Rörelsesensor
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166790. Name from telldus: Uteplats Slinga
[2017-01-30 09:53:08] [Telldus Live!] Creating accessory with ID 1166791. Name from telldus: Uteplats Vägglampor
[2017-01-30 09:53:08] [Telldus Live!] Initializing platform accessory 'Kök'...
[2017-01-30 09:53:08] [Telldus Live!] Initializing platform accessory 'Ute framsidan'...
[2017-01-30 09:53:08] [Telldus Live!] Initializing platform accessory 'Ute framsidan'...
[2017-01-30 09:53:08] [Telldus Live!] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9879f625-6d9e-4397-8ded-0c3225a76ca3
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9879f625-6d9e-4397-8ded-0c3225a76ca3
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at TelldusLive.loginAsync.then.then.accessories (/usr/lib/node_modules/homebridge-telldus/index.js:121:6)
    at tryCatcher (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)`

Here is my config.json in ~/.homebridge/config.json

`
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform" : "Telldus",
            "name" : "Telldus Live!",
	    "public_key" : "XXXXXXX",
	    "private_key" : "XXXXXXX",
	    "token" : "XXXXXXXX",
	    "token_secret" : "XXXXXXX"
        }
    ]
}
`

I have 2 tellstick nets in my account on telldus live, and I think thats why it fails. I must have 2 units to cover the house. One is upstairs and the others downstairs.

Any idea?

**Comment by mifi** [comment]
Try setting different names for the IDs 5338463 and 8998040 using "name" in "unknown_accessories"

See readme and https://github.com/jchnlemon/homebridge-telldus/blob/master/config.json

**Comment by yabbah** [comment]
Worked great, thanks :)

**Comment by misterflippen** [comment]
Hi,
I have the same problem and are trying to sort it out by rename accessories but with no success :( .

- How do I from the log-file find out what divice that conflict that @mifi was able to read out?
- There are some hints at the end of the log but I do not understand where to look to trace warning.

My log-file for the moment looks like this:

[12/25/2020, 10:25:12 AM] [Telldus Liv!e] Initializing Telldus platform...
[12/25/2020, 10:25:12 AM] [Telldus Liv!e] isLocal: false
[12/25/2020, 10:25:12 AM] [Telldus Liv!e] Loading accessories...
[12/25/2020, 10:25:13 AM] [Config] Initializing config platform...
[12/25/2020, 10:25:13 AM] [Config] Running in Service Mode
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Found 6 sensors in telldus live.
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Creating accessory with ID 9026020. Name from telldus: Förrådet
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom config found for ID 9026020.
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom model: 'temperature' overrides 'temperaturehumidity' from telldus
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom manufacturer: 'Nexa' overrides 'undefined' from telldus
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom name: 'Förrådet' overrides 'Förrådet' from telldus
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Creating accessory with ID 9026026. Name from telldus: Förrådsfrysen
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom config found for ID 9026026.
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom model: 'temperature' overrides 'temperature' from telldus
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom manufacturer: 'Nexa' overrides 'undefined' from telldus
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Custom name: 'Förrådsfrysen' overrides 'Förrådsfrysen' from telldus
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Creating accessory with ID 1514694350. Name from telldus: Krypgrunden
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Creating accessory with ID 1514694370. Name from telldus: Ute - Norra sidan
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Creating accessory with ID 10866731. Name from telldus: Uterummet
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Creating accessory with ID 1514643195. Name from telldus: Vinden
[12/25/2020, 10:25:13 AM] [Telldus Liv!e] Found 15 devices in telldus live.
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 1503785. Name from telldus: Balkongfönstret
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 1503747. Name from telldus: Bokhylla1 uppe
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 1592462. Name from telldus: Hallen nere isblocket
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 2073356. Name from telldus: Hallen nere Kartell
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 7179414. Name from telldus: Hallen uppe tak
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom config found for ID 7179414.
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom model: 'selflearning-switch' overrides 'selflearning:cleverio-bulb' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom manufacturer: 'Cleverio' overrides 'undefined' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom name: 'Hallen uppe taklampa' overrides 'Hallen uppe tak' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 2086221. Name from telldus: Kök Vitrinskåp
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 1503820. Name from telldus: Trädgårdsbelysning
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 1708445. Name from telldus: TV-rum Blomma
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 2073354. Name from telldus: TV-rum Kartell
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 2383017. Name from telldus: Uterummet
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 2093131. Name from telldus: vardagsrum julstjärna
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom config found for ID 2093131.
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom model: 'selflearning-switch' overrides 'selflearning-switch:nexa' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom manufacturer: 'Nexa' overrides 'undefined' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom name: 'Vardagsrum Julstjärnor' overrides 'vardagsrum julstjärna' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 7672445. Name from telldus: Vardagsrum julstjärna2
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 2093124. Name from telldus: Vardagsrum LED
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom config found for ID 2093124.
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom model: 'selflearning-switch' overrides 'selflearning-switch:nexa' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom manufacturer: 'Nexa' overrides 'undefined' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Custom name: 'Vardagsrum LED-fönster' overrides 'Vardagsrum LED' from telldus
[12/25/2020, 10:25:16 AM] [Telldus Liv!e] Creating accessory with ID 1305396. Name from telldus: vardagsrum svampen
[12/25/2020, 10:25:16 AM] Initializing platform accessory 'Förrådet'...
[12/25/2020, 10:25:16 AM] Initializing platform accessory 'Förrådsfrysen'...
[12/25/2020, 10:25:16 AM] Initializing platform accessory 'Krypgrunden'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Ute - Norra sidan'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Uterummet'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Vinden'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Balkongfönstret'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Bokhylla1 uppe'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Hallen nere isblocket'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Hallen nere Kartell'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Hallen uppe taklampa'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Kök Vitrinskåp'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Trädgårdsbelysning'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'TV-rum Blomma'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'TV-rum Kartell'...
[12/25/2020, 10:25:17 AM] Initializing platform accessory 'Uterummet'...
[12/25/2020, 10:25:17 AM] [Telldus Liv!e] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c99758a3-e7fd-4825-9369-1988851c7edf
(node:38579) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c99758a3-e7fd-4825-9369-1988851c7edf
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:430:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:417:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at /usr/local/lib/node_modules/homebridge-telldus/index.js:142:6
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38579) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38579) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mifi** [comment]
maybe you have some accessories in telldus live with the same name and need to override them unknown_accessories

**Comment by super-villan** [comment]
Hi , i maybe blind but , i tryd to do as u show in the thread but that did not work for my mifi -**Try setting different names for the IDs 5338463 and 8998040 using "name" in "unknown_accessories"

See readme and https://github.com/jchnlemon/homebridge-telldus/blob/master/config.json**

The error i get is: anyone have time to help me :) ? 
[4/15/2021, 6:12:20 PM] [Telldus Liv!e] [Strip Drip sensor] Your device (model n/a, id 3735712) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 3735712, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[4/15/2021, 6:12:20 PM] [Telldus Liv!e] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: bef4528f-1223-46cc-82a2-325e0bef9c91
(node:13290) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: bef4528f-1223-46cc-82a2-325e0bef9c91
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:547:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-telldus/index.js:142:6
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bigert** [comment]
When I started with HomeBridge, I could not get it to work due to "same UUID issue". Mayby my solution can help someone as a reference.

First I hide all switches in Telldus Live. Then the crash stopped when I started HomeBridge.
Then I added one switch att a time in Telldus live to see when errors occurred, I took that ID and added i config.json.
I soon discovered that it was med Tellstick Z-wave (TZWP-102) that could not be automatic configured). It also seems lika I have to give every item a new unike custom name.


LOG:
[Telldus Live!] [Telldus Z4] Your device (model 0176-0003-0003, id **10299165**) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": **10299165**, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[1/2/2022, 3:01:16 PM] [Telldus Live!] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f0eb631b-1ff3-45cc-9450-3d2607e47
[1/2/2022, 3:01:16 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f0eb631b-1ff3-45cc-9450-3d2607e47
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:583:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:552:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-telldus/index.js:142:6



CONFIG.JSON solution
{
    "bridge": {
        "name": "Homebridge 93xx",
        "username": "0E:CC:C4:66:93:xx",
        "port": 53232,
        "pin": "031-45-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "Telldus",
            "name": "Telldus Live!",
            "public_key": "x",
            "private_key": "x",
            "token": "x",
            "token_secret": "x",
            "unknown_accessories": [
              {
               "id": 10289500,
               "model": "selflearning-switch",
               "manufacturer": "Telldus_Z-wave",
               "name": "Källare_Varmvatten_Telldus_Z3_man"
              },
              {
               "id": 10291300,
               "model": "selflearning-switch",
               "manufacturer": "Telldus_Z-wave",
               "name": "Kök_fönster Z5_man"
              },
              {
               "id": 10282342,
               "model": "selflearning-switch",
               "manufacturer": "Telldus_Z-wave",
               "name": "Lös_telldus_Z2_man"
              },
              {
               "id": 10282337,
               "model": "selflearning-switch",
               "manufacturer": "Telldus_Z-wave",
               "name": "Vardagsrum TV Telldus Z1_man"
              },
              {
               "id": **10299165**,
               "model": "selflearning-switch",
               "manufacturer": "Telldus_Z-wave",
               "name": "Telldus_Z4_man"
              }
           ]
        }
    ],
    "disabledPlugins": [
        "homebridge-telldus-tdtool"
    ]
}
