### ISSUE TITLE
Issue after update to hass.io 0.56

### ISSUE THREAD

**Issue by dasam** [jchnlemon/homebridge-telldus#55]
Been using hass.io with homebridge + telldus live plugin.

After hass.io autoupdated itself to 0.56 it seems it updated homebridge to 2.0. this somehow killed the telldus plugin, or config not sure.

The logs says this error:

[10/22/2017, 8:07:50 PM] Loaded plugin: homebridge-homeassistant
[10/22/2017, 8:07:51 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/22/2017, 8:07:51 PM] ---
[10/22/2017, 8:07:51 PM] ====================
[10/22/2017, 8:07:51 PM] ERROR LOADING PLUGIN homebridge-telldus:
[10/22/2017, 8:07:51 PM] /usr/lib/node_modules/homebridge-telldus/node_modules/telldus-api/index.js:221
        ...oauth.toHeader(oauth.authorize(
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-telldus/index.js:6:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
[10/22/2017, 8:07:51 PM] ====================
[10/22/2017, 8:07:51 PM] Loaded config.json with 0 accessories and 2 platforms.
[10/22/2017, 8:07:51 PM] ---
[10/22/2017, 8:07:51 PM] Loading 2 platforms...
[10/22/2017, 8:07:51 PM] [HomeAssistant] Initializing HomeAssistant platform...
[10/22/2017, 8:07:51 PM] [HomeAssistant] Fetching HomeAssistant devices.
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^
Error: The requested platform 'Telldus' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
/usr/bin/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
Got SIGHUP, reloading.
No service file found in /etc/avahi/services.
write() failed: Broken pipe
Failed to open /etc/resolv.conf: Broken pipe
Got SIGTERM, quitting.

**Comment by mifi** [comment]
Hi. It looks like hass is auto upgrading homebridge then. I just released a new breaking change, going from v0 to v1, which now requires node v8. I think hass needs to upgrade to node 8. Or at least not auto upgrade a dependency to breaking majorversion changes.

**Comment by dasam** [comment]
Well guess it was me who told it to autoupgrade :-(

Do you know what version of Node Hass is on currently?

**Comment by mifi** [comment]
I don't know how your setup looks like. And I don't know how hass.io integrates with homebridge-telldus plugin. Can't you just upgrade installed node to version to 8?

**Comment by dasam** [comment]
Using vanilla hass.io setup ( https://github.com/home-assistant/hassio ) i assume its a stateless docker container..thus i cannot really do anything. Negative side of having no choice of course. See if i can nag the maintainers in discord.

**Comment by mifi** [comment]
I don't understand how it automatically installs `homebridge-telldus`. There has to be an `npm install -g homebridge-telldus` somewhere...
Or have you installed it yourself?

I'm suspecting that this is the line that needs to be changed:
https://github.com/hassio-addons/addon-homebridge/blob/master/homebridge/Dockerfile#L23

**Comment by dasam** [comment]
in the options for homebridge in hass.io you tell it to install the plugins you need:

{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": [
    "homebridge-telldus"
  ],
  "debug": true
}

**Comment by dasam** [comment]
Node will be upgraded to 8 in the next realease (2.10), i will test and see once i get hold of the release.

**Comment by dasam** [comment]
works after upgrading homebridge in hass.io to 2.10!

**Comment by mifi** [comment]
Great. Then I think we can close this?

**Comment by dasam** [comment]
Sure! I got something else after awhile in the log, but thats homebridge related.
