### ISSUE TITLE
Issue with Window blind

### ISSUE THREAD

**Issue by Flawl3ssSWE** [jchnlemon/homebridge-telldus#57]
Hi I just upgraded to new version and now when I try to take my window blind down HomeBridge crashes with the error:

/usr/lib/node_modules/homebridge-telldus/index.js:415
                                                        .asCallback(callback);
                                                         ^

TypeError: api.upDownDevice(...).then(...).asCallback is not a function
    at Characteristic.TargetPosition.cx.on (/usr/lib/node_modules/homebridge-telldus/index.js:415:9)
    at emitMany (events.js:146:13)
    at Characteristic.TargetPosition.emit (events.js:223:7)
    at Characteristic.TargetPosition.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:812:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:757:8)
    at emitMany (events.js:146:13)
    at HAPServer.emit (events.js:223:7)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

How can I fix?

**Comment by mifi** [comment]
Thanks for spotting the bug. I have fixed it now. try newest version 1.0.3

**Comment by Flawl3ssSWE** [comment]
Ok will try it out tomorrow thank you
