### ISSUE TITLE
Crashing when adding new zwave device while running

### ISSUE THREAD

**Issue by dezral** [jchnlemon/homebridge-telldus#59]
i was adding a new siren/bell that runs via zwave, and homebridge Crashed..

**Comment by dezral** [comment]
/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'value' of undefined
    at Characteristic.CurrentTemperature.cx.getValueFromDev.dev [as getValueFromDev] (/usr/local/lib/node_modules/homebridge-telldus/index.js:295:56)
    at bluebird.resolve.asCallback (/usr/local/lib/node_modules/homebridge-telldus/index.js:300:70)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

**Comment by dezral** [comment]
well it is Crashing regardless of what i do now.. did remove the siren..

**Comment by mifi** [comment]
See #58
