### ISSUE TITLE
error with 1.0.4

### ISSUE THREAD

**Issue by dasam** [jchnlemon/homebridge-telldus#60]
Got this error after reboot of home assistant.  Seems related to latest version.

[cont-init.d] 82-user-plugins.sh: executing... 
+ homebridge-telldus@1.0.4
.
.
[2017-11-14 23:25:50] ERROR LOADING PLUGIN homebridge-telldus:
[2017-11-14 23:25:50] Error: Plugin /usr/lib/node_modules/homebridge-telldus does not contain the 'homebridge' package in 'engines'.
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:49:11)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:134:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:130:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:55:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by mifi** [comment]
Sorry, I messed up. It seems homebridge is using a non-standard engines field, which causes yarn to complain. I reverted this now in 1.0.5. Try upgrading

**Comment by dasam** [comment]
@mifi works again!

**Comment by mifi** [comment]
great, sry about that
